### ISSUE TITLE
Keeping the rating persistent

### ISSUE THREAD

**Issue by hrishikesh-k** [YanNerio/emotion-ratings#8]
How can we keep the rating persistent across page reloads?

**Comment by peter-mghendi** [comment]
I would think that this is beyond the scope of this plugin. Use GET parameters or [cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) with the callback function.

**Comment by hrishikesh-k** [comment]
Okay, great. Thanks for the info.
